### ISSUE TITLE
New example: drake + magick to render images in knitr

### ISSUE THREAD

**Issue by wlandau** [wlandau/drake-examples#38]
https://github.com/ropensci/drake/issues/1126#issuecomment-569845228

**Comment by wlandau-lilly** [comment]
Too much overall rendering time. Not a great plan, as it turns out.

**Comment by RobertMyles** [comment]
Hi @wlandau ,

I've been using drake recently for the first time (amazing btw, thank you!) and I've been struggling a little bit with the approach you outlined in the link above, and also with the alternative mentioned in the thread, i.e. using `ggsave()`. 

I would ideally prefer to use your `ggmem()` approach, as the report I'm making then has dependencies on the plots, as I think it should. Using the `file_out()` approach with `ggsave()` means my report does not have a dependency on these plots anymore. If I change something in the plot code, I then have to make an explicit change in the report to make it update (I'm not using a trigger for the report). 

However, using the `ggmem()` approach, I ran into real problems trying to size the plots effectively. I couldn't really gain any real control over how they were sized (they all came out too small with the plot elements far too big), whereas with ggsave, it's just a matter of passing parameters to the function.

Am I missing something here with the way drake works with images being generated for a report like this? Being new to the package, I think I may have misunderstood. 

Also, I've posted here so as not to spam the other thread, happy to move the conversation over there if you think it's a better place for it.

**Comment by wlandau** [comment]
Hi Robert, glad you like the package.

I think I was too hasty to recommend `magick` for this because, like you said, it is hard to control the rendering. Plus, rendering happens more slowly than for `ggsave()`.

`file_out()` is a bit difficult to make work with reports. There is a way to do it: put `file_in()` in the command in the plan that renders the report. However, [dynamic files](https://books.ropensci.org/drake/plans.html#dynamic-files) are probably easier for this. You can define a dynamic file for your plot target like in this sketch:

```{r}
save_plot_and_return_path <- function(data) { # custom
  plot <- ggplot(data) + ...
  ggsave(plot, "plot_file.png")
  return("plot_file.png")
}

plan <- drake_plan(
  ...,
  plot_file = target(
    save_plot_and_return_path(data)
  )
)
```

Then in your report, you can mention the dynamic file with `readd(plot_file)` in a code chunk. When the file changes, the report will automatically update in `make()`.

**Comment by RobertMyles** [comment]
Hi Will,
Thanks for getting back to me. I'm working through your suggestions with my real-life project, but I'm getting snagged on actually rendering the plot in the report, as opposed to printing the filename, which is what is currently happening. I've made a reprex which shows the problem:


``` r
library(drake)
library(ggplot2)
library(tibble)
library(rmarkdown)

save_plot_and_return_path <- function(data) { # custom
  plot <- ggplot(data, aes(x = cyl, y = wt)) + geom_boxplot()
  ggsave(plot = plot, filename = "plot_file.png", device = "png")
  return("plot_file.png")
}

make_df <- function() {
  df <- tibble(
    wt = rnorm(50, 2.5, 1),
    cyl = sample(c("4", "6", "8"), 50, replace = TRUE)
  )
}

plan <- drake_plan(
  data = make_df(),
  plot_file = target(
    save_plot_and_return_path(data),
    format = "file"
  ),
  make_report = render(
    knitr_in("example.Rmd"),
    output_file = file_out("example.pdf"),
    quiet = TRUE
  )
)
# vis_drake_graph(plan)
make(plan)
#> ✓ All targets are already up to date.
```

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


The simple plan looks like this: 

<img width="955" alt="Screenshot 2020-07-03 at 14 37 59" src="https://user-images.githubusercontent.com/7211207/86474563-01415380-bd3b-11ea-8c3c-75c10c379ffa.png">

My rmarkdown file contains the following (the two backticks on the code chunk are just for formatting here): 

```
---
title: "Drake Example"
author: "Robert McDonnell"
date: "7/3/2020"
output: pdf_document
---

``{r}
readd(plot_file)
``

```



However, the PDF looks like this: 
<img width="1043" alt="Screenshot 2020-07-03 at 14 40 22" src="https://user-images.githubusercontent.com/7211207/86474788-77de5100-bd3b-11ea-90db-eb77aaa3a715.png">

Meaning I'm still getting a print-out of the file name, rather than the image. I've tried including the filename as shown [here](https://books.ropensci.org/drake/plans.html#dynamic-files) (i.e. "my file"), but that didn't seem to make any difference.

I hope I'm not making some basic error here, and I really appreciate you taking time to help me out with this!

**Comment by wlandau** [comment]
So maybe I left out a couple things. Dynamic file targets return the file path by default, so what you are seeing from `readd(plot_file)` is actually correct. To render the actual image in the report, the easiest way is probably to write `webshot::webshot(readd(plot_file))`. Alternatives include the Markdown syntax `![](./plot_file.png)` or an HTML `<img>` tag. Either way, we still need `readd(plot_file)` or `loadd(plot_file)` so `drake` knows that the report depends on the plot.

**Comment by RobertMyles** [comment]
Thanks, Will, I finally got it to work.

Unfortunately, `webshot::webshot(readd(plot_file))` is giving me [this](https://github.com/wch/webshot/issues/91) mysterious error, but by using [pander](https://www.r-project.org/nosvn/pandoc/pander.html), I was able to get what I wanted.

Using:

```markdown

```{r results='asis'}
pander::pandoc.image.return(readd(plot_file))
```
 in the code chunk worked perfectly, and the plan has the dependencies like I wanted.

Thanks for your help, Will, and perhaps for other users, recommending pander as above might be of help.

Rob
